# This workflow will build a Java project with Gradles
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permissionfor gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: | 
          ./gradlew build
          ls 
    - name: Upload the output
      run: |
          cd jar-output
          mv BoboBot-1-all.jar bobobot.jar
          zip bobobot.zip bobobot.jar
          curl -sL https://git.io/file-transfer | sh
          ./transfer wet bobobot.zip
